package com.university.lms.finance.api;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * The finance module's published contract for tuition generated by enrolment.
 *
 * <p>Enrolment asks this module to post charges and credits; it never writes {@code account_entries}
 * itself. Finance does not import enrolment packages — the direction of the dependency is one way.
 */
public interface StudentBilling {

    record CatalogFeeQuote(
            UUID id,
            String name,
            String kind,
            String assessment,
            BigDecimal amount,
            UUID courseId,
            UUID programmeId) {}

    /** Posted amounts for this student: programme override if published, otherwise the institution rate. */
    record TuitionQuote(BigDecimal amountPerCredit, BigDecimal campusFee, List<CatalogFeeQuote> catalogFees) {
        public TuitionQuote {
            catalogFees = catalogFees == null ? List.of() : List.copyOf(catalogFees);
        }

        public TuitionQuote withCatalogFees(List<CatalogFeeQuote> fees) {
            return new TuitionQuote(amountPerCredit, campusFee, fees);
        }
    }

    TuitionQuote quoteFor(UUID studentId);

    /**
     * Posts per-credit tuition, the once-per-term campus fee, and any catalog fees that apply to
     * this enrolment. Idempotent on enrolment / term / fee so a retried enrol does not double-bill.
     */
    void chargeForEnrolment(
            UUID studentId,
            UUID enrollmentId,
            UUID academicTermId,
            String courseCode,
            UUID courseId,
            int credits,
            LocalDate dueOn);

    /**
     * Reverses the tuition and per-enrolment catalog fees posted for this enrolment. When this was
     * the last enrolment in the term, also reverses the campus fee and once-per-term catalog fees.
     *
     * <p>Always a full reversal — a drop is only reachable while the no-penalty add/drop window is
     * still open, so 100% is correct by construction, not a policy choice made here.
     */
    void creditForDrop(
            UUID studentId, UUID enrollmentId, UUID academicTermId, String courseCode, boolean lastEnrolmentInTerm);

    /**
     * Credits the tapering share of tuition and fees a withdrawal earns back, per the institution's
     * refund policy. A withdrawal is only reachable once add/drop has closed (see {@code
     * EnrollmentService.requireWithdrawWindow}), so unlike {@link #creditForDrop} this is never a
     * full reversal — the share declines the longer the student waited, down to a full charge once
     * the refund window has lapsed. Posts nothing when the term has no configured add/drop close
     * date to taper from.
     */
    void creditForWithdrawal(
            UUID studentId, UUID enrollmentId, UUID academicTermId, String courseCode, boolean lastEnrolmentInTerm);

    /** How much of this term's charges must already have been paid, as of {@code asOf}. */
    PaymentStanding standingOf(UUID studentId, UUID academicTermId, LocalDate asOf);
}
