package com.university.lms.finance.api;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * The finance module's published contract for tuition generated by enrolment.
 *
 * <p>Enrolment asks this module to post charges and credits; it never writes {@code account_entries}
 * itself. Finance does not import enrolment packages — the direction of the dependency is one way.
 */
public interface StudentBilling {

    record CatalogFeeQuote(
            UUID id,
            String name,
            String kind,
            String assessment,
            BigDecimal amount,
            UUID courseId,
            UUID programmeId) {}

    /** Posted amounts for this student: programme override if published, otherwise the institution rate. */
    record TuitionQuote(BigDecimal amountPerCredit, BigDecimal campusFee, List<CatalogFeeQuote> catalogFees) {
        public TuitionQuote {
            catalogFees = catalogFees == null ? List.of() : List.copyOf(catalogFees);
        }

        public TuitionQuote withCatalogFees(List<CatalogFeeQuote> fees) {
            return new TuitionQuote(amountPerCredit, campusFee, fees);
        }
    }

    TuitionQuote quoteFor(UUID studentId);

    /**
     * Posts per-credit tuition, the once-per-term campus fee, and any catalog fees that apply to
     * this enrolment. Idempotent on enrolment / term / fee so a retried enrol does not double-bill.
     */
    void chargeForEnrolment(
            UUID studentId,
            UUID enrollmentId,
            UUID academicTermId,
            String courseCode,
            UUID courseId,
            int credits,
            LocalDate dueOn);

    /**
     * Reverses the tuition and per-enrolment catalog fees posted for this enrolment. When this was
     * the last enrolment in the term, also reverses the campus fee and once-per-term catalog fees.
     */
    void creditForDrop(
            UUID studentId, UUID enrollmentId, UUID academicTermId, String courseCode, boolean lastEnrolmentInTerm);

    /** How much of this term's charges must already have been paid, as of {@code asOf}. */
    PaymentStanding standingOf(UUID studentId, UUID academicTermId, LocalDate asOf);
}
