package com.university.lms.request.domain;

import com.university.lms.common.exception.ErrorCode;

public enum RequestErrorCode implements ErrorCode {
    REQUEST_NOT_FOUND,
    REQUEST_ALREADY_OPEN,
    REQUEST_ALREADY_DECIDED,
    REQUEST_INVALID_DECISION,
    REQUEST_INVALID_TRANSITION,
    REQUEST_INVALID_PAYLOAD,
    REQUEST_NOT_ASSIGNED,
    REQUEST_DELIVERABLE_REQUIRED,
    REQUEST_FULFILLMENT_FAILED,
    REQUEST_CLOSED,
    REQUEST_REASSIGN_NOT_PERMITTED,
    REQUEST_REASSIGN_TARGET_NOT_FOUND,
    REQUEST_ATTACHMENT_FILE_REQUIRED,
    REQUEST_ATTACHMENT_TOO_LARGE,
    REQUEST_ATTACHMENT_TYPE_NOT_ALLOWED,
    REQUEST_ATTACHMENT_NOT_FOUND;

    @Override
    public String code() {
        return name();
    }
}
